apps:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/**"

workers:
  - changed-files:
      - any-glob-to-any-file:
          - "workers/**"

extensions:
  - changed-files:
      - any-glob-to-any-file:
          - "extensions/**"

packages:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/**"

github-config:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"
